Combine tests
Signed-off-by: Ben Howe <bhowe@nvidia.com>

diff --git a/.github/workflows/build_wheels.yaml b/.github/workflows/build_wheels.yaml
--- a/.github/workflows/build_wheels.yaml
+++ b/.github/workflows/build_wheels.yaml
@@ -231,7 +231,7 @@ jobs:
       matrix:
         python: ['3.11', '3.12', '3.13']
         platform: ['amd64', 'arm64']
-        cuda_version: ['12.6', '13.0']
+        cuda_version: ['12.6'] # intentionally not 13.0 because this is CPU.
   
     steps:
       - name: Get code
@@ -382,111 +382,111 @@ jobs:
       #     name: core-files-${{ matrix.python }}-arm64
       #     path: core.*
 
-  test-wheels-gpu-cudaqx-metapackages:
-    name: Test Meta Packages
-    needs: [build-cudaqx-wheels, build-cudaq-wheels, build-cudaqx-metapackages]
-    if: ${{ !failure() && !cancelled() }}
-    runs-on: linux-${{ matrix.runner.arch }}-gpu-${{ matrix.runner.gpu }}-latest-1
-    container:
-      image: nvidia/cuda:${{ matrix.cuda_version }}.0-base-ubuntu24.04
-      # Enable this if you want to collect core files. (You may might to enable
-      # Debug builds if you're doing this.)
-      #options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
-      env:
-        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
-    permissions:
-      actions: write
-      contents: read
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [
-          { arch: arm64, gpu: a100 },
-          { arch: amd64, gpu: a100 },
-        ]
-        python: ['3.11', '3.12', '3.13']
-        cuda_version: ['12.6', '13.0']
-        lib: ['solvers', 'qec']
+  # test-wheels-gpu-cudaqx-metapackages:
+  #   name: Test Meta Packages
+  #   needs: [build-cudaqx-wheels, build-cudaq-wheels, build-cudaqx-metapackages]
+  #   if: ${{ !failure() && !cancelled() }}
+  #   runs-on: linux-${{ matrix.runner.arch }}-gpu-${{ matrix.runner.gpu }}-latest-1
+  #   container:
+  #     image: nvidia/cuda:${{ matrix.cuda_version }}.0-base-ubuntu24.04
+  #     # Enable this if you want to collect core files. (You may might to enable
+  #     # Debug builds if you're doing this.)
+  #     #options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
+  #     env:
+  #       NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
+  #   permissions:
+  #     actions: write
+  #     contents: read
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       runner: [
+  #         { arch: arm64, gpu: a100 },
+  #         { arch: amd64, gpu: a100 },
+  #       ]
+  #       python: ['3.11', '3.12', '3.13']
+  #       cuda_version: ['12.6', '13.0']
+  #       lib: ['solvers', 'qec']
   
-    steps:
-      - name: Get code
-        uses: actions/checkout@v4
-        with:
-          set-safe-directory: true
+  #   steps:
+  #     - name: Get code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         set-safe-directory: true
   
-      - name: Configure
-        id: config
-        run: |
-          cuda_major=`echo ${{ matrix.cuda_version }} | cut -d . -f1`
-          echo "cuda_major=$cuda_major" >> $GITHUB_OUTPUT
-          echo "run_id_to_use=${{ inputs.artifacts_from_run || github.run_id }}" >> $GITHUB_OUTPUT
-          if [ -n "${{ inputs.artifacts_from_run }}" ]; then
-            echo "Using artifacts from workflow id ${{ inputs.artifacts_from_run }}" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "Using artifacts from this run (id ${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
-          fi
+  #     - name: Configure
+  #       id: config
+  #       run: |
+  #         cuda_major=`echo ${{ matrix.cuda_version }} | cut -d . -f1`
+  #         echo "cuda_major=$cuda_major" >> $GITHUB_OUTPUT
+  #         echo "run_id_to_use=${{ inputs.artifacts_from_run || github.run_id }}" >> $GITHUB_OUTPUT
+  #         if [ -n "${{ inputs.artifacts_from_run }}" ]; then
+  #           echo "Using artifacts from workflow id ${{ inputs.artifacts_from_run }}" >> $GITHUB_STEP_SUMMARY
+  #         else
+  #           echo "Using artifacts from this run (id ${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
+  #         fi
 
-      - name: Install Python ${{ matrix.python }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python }}
+  #     - name: Install Python ${{ matrix.python }}
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python }}
   
-      - name: Install requirements
-        shell: bash
-        run: |
-          apt update
-          apt install -y --no-install-recommends libgfortran5 unzip openmpi-bin libopenmpi3
-          # If this is x86_64, then install libquadmath0. This is normally
-          # installed by Ubuntu Python, but the action/setup-python package does
-          # not install it.
-          if [ "$(uname -m)" == "x86_64" ]; then
-            apt install -y --no-install-recommends libquadmath0
-          fi
-          #echo 'core.%p' | tee /proc/sys/kernel/core_pattern
-          #echo "Running cat /proc/sys/kernel/core_pattern"
-          #cat /proc/sys/kernel/core_pattern
+  #     - name: Install requirements
+  #       shell: bash
+  #       run: |
+  #         apt update
+  #         apt install -y --no-install-recommends libgfortran5 unzip openmpi-bin libopenmpi3
+  #         # If this is x86_64, then install libquadmath0. This is normally
+  #         # installed by Ubuntu Python, but the action/setup-python package does
+  #         # not install it.
+  #         if [ "$(uname -m)" == "x86_64" ]; then
+  #           apt install -y --no-install-recommends libquadmath0
+  #         fi
+  #         #echo 'core.%p' | tee /proc/sys/kernel/core_pattern
+  #         #echo "Running cat /proc/sys/kernel/core_pattern"
+  #         #cat /proc/sys/kernel/core_pattern
   
-      - name: Download CUDA-Q wheels
-        if: ${{ inputs.cudaq_wheels == 'Custom' }}
-        uses: actions/download-artifact@v4
-        with:
-          name: cudaq-wheels-${{ matrix.runner.arch }}-cu${{ steps.config.outputs.cuda_major }}
-          path: /cudaq-wheels
-          run-id: ${{ steps.config.outputs.run_id_to_use }}
-          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+  #     - name: Download CUDA-Q wheels
+  #       if: ${{ inputs.cudaq_wheels == 'Custom' }}
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: cudaq-wheels-${{ matrix.runner.arch }}-cu${{ steps.config.outputs.cuda_major }}
+  #         path: /cudaq-wheels
+  #         run-id: ${{ steps.config.outputs.run_id_to_use }}
+  #         github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
 
-      - name: Download CUDA-QX Meta Packages
-        uses: actions/download-artifact@v4
-        with:
-          name: metapackages
-          path: /metapackages
-          run-id: ${{ steps.config.outputs.run_id_to_use }}
-          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+  #     - name: Download CUDA-QX Meta Packages
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: metapackages
+  #         path: /metapackages
+  #         run-id: ${{ steps.config.outputs.run_id_to_use }}
+  #         github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
 
-      - name: Download CUDA-QX wheels
-        uses: actions/download-artifact@v4
-        with:
-          pattern: wheels-py${{ matrix.python }}-${{ matrix.runner.arch }}-cu${{ steps.config.outputs.cuda_major }}
-          merge-multiple: true
-          path: /wheels
-          run-id: ${{ steps.config.outputs.run_id_to_use }}
-          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+  #     - name: Download CUDA-QX wheels
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: wheels-py${{ matrix.python }}-${{ matrix.runner.arch }}-cu${{ steps.config.outputs.cuda_major }}
+  #         merge-multiple: true
+  #         path: /wheels
+  #         run-id: ${{ steps.config.outputs.run_id_to_use }}
+  #         github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
   
-      - name: Test Meta Packages (${{ matrix.lib }})
-        shell: bash
-        run: |
-          for d in /metapackages /wheels /cudaq-wheels; do
-            echo "ls $d"
-            ls $d
-          done
-          python${{ matrix.python }} -m pip install --find-links /metapackages/ --find-links /wheels/ --find-links /cudaq-wheels/ cudaq-${{ matrix.lib }}==0.99.99
-          # Verify that the correct package was installed.
-          package_installed=$(python${{ matrix.python }} -m pip list | grep cudaq-${{ matrix.lib }}-cu | cut -d ' ' -f1)
-          package_expected=cudaq-${{ matrix.lib }}-cu${{ steps.config.outputs.cuda_major }}
-          if [ "$package_installed" != "$package_expected" ]; then
-            echo "::error Expected installation of $package_expected package, but got $package_installed."
-            exit 1
-          fi
+  #     - name: Test Meta Packages (${{ matrix.lib }})
+  #       shell: bash
+  #       run: |
+  #         for d in /metapackages /wheels /cudaq-wheels; do
+  #           echo "ls $d"
+  #           ls $d
+  #         done
+  #         python${{ matrix.python }} -m pip install --find-links /metapackages/ --find-links /wheels/ --find-links /cudaq-wheels/ cudaq-${{ matrix.lib }}==0.99.99
+  #         # Verify that the correct package was installed.
+  #         package_installed=$(python${{ matrix.python }} -m pip list | grep cudaq-${{ matrix.lib }}-cu | cut -d ' ' -f1)
+  #         package_expected=cudaq-${{ matrix.lib }}-cu${{ steps.config.outputs.cuda_major }}
+  #         if [ "$package_installed" != "$package_expected" ]; then
+  #           echo "::error Expected installation of $package_expected package, but got $package_installed."
+  #           exit 1
+  #         fi
 
       # - name: Upload any core files
       #   if: success() || failure()
