.
Signed-off-by: Ben Howe <bhowe@nvidia.com>

diff --git a/.github/workflows/build_wheels.yaml b/.github/workflows/build_wheels.yaml
--- a/.github/workflows/build_wheels.yaml
+++ b/.github/workflows/build_wheels.yaml
@@ -132,6 +132,7 @@ jobs:
 
   build-cudaqx-metapackages:
     name: Build CUDA-QX Meta Packages
+    if: ${{ !inputs.artifacts_from_run }}
     runs-on: linux-amd64-cpu4 # No need to matrix this because it is a source distribution
     container: ubuntu:24.04
     permissions:
@@ -460,6 +461,13 @@ jobs:
             ls $d
           done
           python${{ matrix.python }} -m pip install --find-links /metapackages/ --find-links /wheels/ --find-links /cudaq-wheels/ cudaq-${{ matrix.lib }}==0.0.0
+          # Verify that the correct package was installed.
+          package_installed=$(${python} -m pip list | grep cudaq-${{ matrix.lib }})
+          package_expected=cudaq-${{ matrix.lib }}-cu${{ steps.config.outputs.cuda_major }}
+          if [ "$package_installed" != "$package_expected" ]; then
+            echo "::error Expected installation of $package_expected package, but got $package_installed."
+            exit 1
+          fi
 
       # - name: Upload any core files
       #   if: success() || failure()
